=== webstyle-directory/website/style-libraries.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": ["githubUrl"],
    "properties": {
      "githubUrl": {
        "$id": "#/items/properties/githubUrl",
        "type": "string",
        "title": "The Githuburl Schema",
        "default": "",
        "examples": ["https://github.com/webstyle-directory/website"],
        "pattern": "^(.*)$"
      },
      "uiComponents": {
        "$id": "#/items/properties/uiComponents",
        "type": "boolean",
        "title": "The uiComponents Schema",
        "default": false,
        "examples": [true]
      },
      "templates": {
        "$id": "#/items/properties/templates",
        "type": "boolean",
        "title": "The templates Schema",
        "default": false,
        "examples": [true]
      },
      "scss": {
        "$id": "#/items/properties/scss",
        "type": "boolean",
        "title": "The scss Schema",
        "default": false,
        "examples": [true]
      },
      "less": {
        "$id": "#/items/properties/less",
        "type": "boolean",
        "title": "The less Schema",
        "default": false,
        "examples": [true]
      },
      "vanilacss": {
        "$id": "#/items/properties/vanilacss",
        "type": "boolean",
        "title": "The vanilacss Schema",
        "default": false,
        "examples": [true]
      },
      "react": {
        "$id": "#/items/properties/react",
        "type": "boolean",
        "title": "The react Schema",
        "default": false,
        "examples": [true]
      },
      "angular": {
        "$id": "#/items/properties/angular",
        "type": "boolean",
        "title": "The angular Schema",
        "default": false,
        "examples": [true]
      },
      "vue": {
        "$id": "#/items/properties/vue",
        "type": "boolean",
        "title": "The vue Schema",
        "default": false,
        "examples": [true]
      },
      "examples": {
        "$id": "#/items/properties/examples",
        "type": "array",
        "title": "The Examples Schema",
        "default": null,
        "items": {
          "$id": "#/items/properties/examples/items",
          "type": "string",
          "title": "The Items Schema",
          "default": "",
          "examples": ["https://snack.expo.io/SkRP2Ehrb"],
          "pattern": "^(.*)$"
        }
      },
      "npmPkg": {
        "$id": "#/items/properties/npmPkg",
        "type": "string",
        "title": "The Npmpkg Schema",
        "default": "",
        "examples": ["@expo/ex-navigation"],
        "pattern": "^(.*)$"
      },
      "unmaintained": {
        "$id": "#/items/properties/unmaintained",
        "type": "boolean",
        "title": "The Unmaintained Schema",
        "default": false,
        "examples": [true]
      },
      "images": {
        "$id": "#/items/properties/images",
        "type": "array",
        "title": "The Images Schema",
        "default": [null],
        "items": {
          "$id": "#/items/properties/images/items",
          "type": "string",
          "title": "The Image Schema",
          "default": "",
          "examples": ["https://reactnative.dev/img/homepage/phones.png"],
          "pattern": "^(http(s?):)([/|.|\\w|\\s|-])*\\.(?:jpg|gif|png)$"
        }
      },
      "nameOverride": {
        "$id": "#/items/properties/nameOverride",
        "type": "string",
        "title": "Optional property to override the name provided by npm and GitHub",
        "default": "",
        "examples": ["react-navigation"],
        "pattern": "^(.*)$"
      },
      "dev": {
        "$id": "#/items/properties/dev",
        "type": "boolean",
        "title": "The Development Tool Schema",
        "default": false,
        "examples": [true]
      }
    }
  }
}

=== webstyle-directory/website/react-native-libraries.json
[
  {
    "githubUrl": "https://github.com/twbs/bootstrap",
    "uiComponents": true,
    "templates": true,
    "scss": true,
    "less": false,
    "vanilacss": false
  },
  {
    "githubUrl": "https://github.com/pure-css/pure",
    "uiComponents": true,
    "templates": true,
    "scss": false,
    "less": false,
    "vanilacss": true
  },
  {
    "githubUrl": "https://github.com/vmware/clarity",
    "uiComponents": true,
    "templates": true,
    "scss": false,
    "less": false,
    "vanilacss": true,
    "angular": true
  },
  {
    "githubUrl": "https://github.com/mui-org/material-ui",
    "uiComponents": true,
    "templates": true,
    "scss": false,
    "less": false,
    "vanilacss": false,
    "react": true
  },
  {
    "githubUrl": "https://github.com/vmware/clarity",
    "npmPkg": "@clr/angular",
    "uiComponents": true,
    "templates": true,
    "scss": false,
    "less": false,
    "vanilacss": true,
    "angular": true
  },
  {
    "githubUrl": "https://github.com/uber/baseweb",
    "uiComponents": true,
    "templates": true,
    "scss": false,
    "less": false,
    "vanilacss": false,
    "react": true
  }
]

=== webstyle-directory/website/style-libraries.json
[
  {
    "githubUrl": "https://github.com/twbs/bootstrap",
    "uiComponents": true,
    "templates": true,
    "scss": true
  },
  {
    "githubUrl": "https://github.com/pure-css/pure",
    "uiComponents": true,
    "templates": true,
    "vanilacss": true
  },
  {
    "githubUrl": "https://github.com/mui-org/material-ui",
    "uiComponents": true,
    "templates": true,
    "react": true
  },
  {
    "githubUrl": "https://github.com/vmware/clarity",
    "npmPkg": "@clr/angular",
    "uiComponents": true,
    "templates": true,
    "vanilacss": true,
    "angular": true
  },
  {
    "githubUrl": "https://github.com/uber/baseweb",
    "uiComponents": true,
    "templates": true,
    "react": true
  },
  {
    "githubUrl": "https://github.com/foundation/foundation-sites",
    "uiComponents": true,
    "templates": true,
    "scss": true,
    "vanilacss": true
  },
  {
    "githubUrl": "https://github.com/getbase/base",
    "templates": true,
    "scss": true,
    "less": true,
    "vanilacss": true
  },
  {
    "githubUrl": "https://github.com/jgthms/bulma",
    "uiComponents": true,
    "templates": true,
    "scss": true,
    "vanilacss": true
  },
  {
    "githubUrl": "https://github.com/couds/react-bulma-components",
    "uiComponents": true,
    "scss": true,
    "react": true
  },
  {
    "githubUrl": "https://github.com/react-bootstrap/react-bootstrap",
    "uiComponents": true,
    "react": true
  },
  {
    "githubUrl": "https://github.com/ng-bootstrap/ng-bootstrap",
    "uiComponents": true,
    "angular": true
  },
  {
    "githubUrl": "https://github.com/reactstrap/reactstrap",
    "uiComponents": true,
    "react": true
  },
  {
    "githubUrl": "https://github.com/bootstrap-vue/bootstrap-vue",
    "uiComponents": true,
    "vue": true
  },
  {
    "githubUrl": "https://github.com/dhg/Skeleton",
    "uiComponents": true,
    "vanilacss": true
  },
  {
    "githubUrl": "https://github.com/uikit/uikit",
    "uiComponents": true,
    "scss": true,
    "less": true,
    "vanilacss": true
  },
  {
    "githubUrl": "https://github.com/microsoft/fluentui",
    "uiComponents": true,
    "react": true
  },
  {
    "githubUrl": "https://github.com/olton/Metro-UI-CSS",
    "uiComponents": true,
    "less": true,
    "vanilacss": true
  },
  {
    "githubUrl": "https://github.com/ant-design/ant-design",
    "uiComponents": true,
    "less": true,
    "vanilacss": true,
    "react": true
  },
  {
    "githubUrl": "https://github.com/NG-ZORRO/ng-zorro-antd",
    "uiComponents": true,
    "less": true,
    "vanilacss": true,
    "angular": true
  },
  {
    "githubUrl": "https://github.com/tailwindlabs/tailwindcss",
    "uiComponents": true,
    "vanilacss": true
  },
  {
    "githubUrl": "https://github.com/grommet/grommet",
    "uiComponents": true,
    "react": true
  },
  {
    "githubUrl": "https://github.com/Shopify/polaris-react",
    "uiComponents": true,
    "react": true
  }
]
